name: CI - TensorFlow Image Classification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # Configura o Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Instala as dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow matplotlib pillow requests numpy

      # Executa o script principal
      - name: Run image classification
        run: python main.py
